# Generated by Django 5.2.8 on 2025-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(db_index=True, help_text='약품 제품명', max_length=200)),
                ('age_group', models.IntegerField(db_index=True, help_text='재분류된 연령대 그룹(0, 1, 2)')),
                ('avg_daily_dose', models.FloatField(help_text='그룹별 평균 1일 투약량')),
            ],
            options={
                'verbose_name': '의약품처방 기준 통계',
                'unique_together': {('drug_name', 'age_group')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(db_index=True, help_text='주상병 이름', max_length=200)),
                ('dept', models.CharField(db_index=True, help_text='진료과목 이름', max_length=20)),
                ('age_group', models.IntegerField(db_index=True, help_text='재분류된 연령대 그룹(0, 1, 2)')),
                ('avg_fee', models.IntegerField(help_text='그룹별 평균 심결본인부담금')),
                ('avg_days', models.FloatField(help_text='그룹별 평균 총 처방일수')),
            ],
            options={
                'verbose_name': '진료내역 기준 통계',
                'unique_together': {('disease', 'dept', 'age_group')},
            },
        ),
    ]
