# Generated by Django 5.2.8 on 2025-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstandard',
            name='age_group',
            field=models.CharField(max_length=50, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='treatmentstandard',
            name='age_group',
            field=models.CharField(max_length=50, verbose_name='연령대'),
        ),
    ]
