# Generated by Django 5.2.8 on 2025-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_alter_drugstandard_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstandard',
            name='avg_daily_dose',
            field=models.FloatField(verbose_name='그룹별 평균 1일 투약량'),
        ),
        migrations.AlterField(
            model_name='drugstandard',
            name='drug_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='약품 제품명'),
        ),
        migrations.AlterField(
            model_name='treatmentstandard',
            name='avg_days',
            field=models.FloatField(verbose_name='그룹별 평균 총 처방일수'),
        ),
        migrations.AlterField(
            model_name='treatmentstandard',
            name='avg_fee',
            field=models.FloatField(verbose_name='그룹별 평균 심결본인부담금'),
        ),
        migrations.AlterField(
            model_name='treatmentstandard',
            name='dept',
            field=models.CharField(db_index=True, max_length=20, verbose_name='진료과목 이름'),
        ),
        migrations.AlterField(
            model_name='treatmentstandard',
            name='disease',
            field=models.CharField(db_index=True, max_length=200, verbose_name='주상병'),
        ),
    ]
