# Generated by Django 5.2.8 on 2025-11-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_alter_drugstandard_avg_daily_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstandard',
            name='sample_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='표본 수'),
        ),
    ]
