# Generated by Django 5.2.8 on 2025-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_drugstandard_sample_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstandard',
            name='avg_daily_dose',
        ),
        migrations.AddField(
            model_name='drugstandard',
            name='avg_total_dose',
            field=models.FloatField(default=0.0, verbose_name='그룹별 평균 총 투약량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentstandard',
            name='sample_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='표본 수'),
        ),
    ]
