# Generated by Django 5.2.8 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0005_remove_drugstandard_avg_daily_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentstandard',
            name='disease_name',
            field=models.CharField(db_index=True, default=0.0, max_length=200, verbose_name='주상병 이름'),
            preserve_default=False,
        ),
    ]
