# Generated by Django 5.2.8 on 2025-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0006_treatmentstandard_disease_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, unique=True, verbose_name='주상병 코드')),
                ('disease_name', models.CharField(max_length=255, verbose_name='질병명')),
            ],
            options={
                'verbose_name': '질병 코드 매핑 데이터',
                'indexes': [models.Index(fields=['disease_name'], name='standards_d_disease_69f55a_idx')],
            },
        ),
    ]
